//! High-level facade for AI agents.
//!
//! The agent doesn't need to know about chain weights, power schedules,
//! or signal classifiers. It just picks a vulnerability class and a target.
//!
//! ```ignore
//! let result = Fuzzer::new(my_probe)
//!     .sql_injection()
//!     .target("https://example.com/search?q=", "GET")
//!     .budget(100)
//!     .run()
//!     .await
//!     .unwrap();
//! // result.confirmed: Vec<Hit> — all confirmed SQLi payloads
//! ```

use std::sync::Arc;
use async_trait::async_trait;
use url::Url;

use crate::baseline::BaselineProfile;
use crate::evolutionary::*;
use crate::payloads;
use crate::signals::signal::*;
use crate::signals::{Probe, Request, ProbeResponse};
use std::collections::HashMap;
use std::time::Duration;

// ── Arc blanket impl for Probe ──────────────────────────────────────────

#[async_trait]
impl<P: Probe> Probe for Arc<P> {
    async fn send(&self, req: &Request) -> Result<ProbeResponse, String> {
        self.as_ref().send(req).await
    }
}

// ── Hit (simplified for agent consumption) ──────────────────────────────

/// Where a hit came from — useful for agent reasoning and audit trails.
#[derive(Debug, Clone)]
pub enum PayloadSource {
    /// From a built-in payload table.  e.g. `("sqli", 14)` = SQLI_PAYLOADS[14].
    Table { preset: String, index: usize },
    /// User-supplied payload (InputsOnly mode).
    UserInput { index: usize },
    /// Generated by the evolutionary engine (no fixed provenance).
    Evolutionary,
}

/// A single confirmed or interesting hit, simplified for agent readability.
#[derive(Debug, Clone)]
pub struct Hit {
    /// The payload string that triggered the hit.
    pub payload: String,
    /// Raw score from the feedback layer (0–6 for HttpFeedback).
    pub raw_score: u8,
    /// Confidence from baseline profiling (0.0 = unreliable, 1.0 = clean).
    pub confidence: f32,
    /// Adjusted score = raw_score × confidence.
    pub adjusted_score: f32,
    /// True if this is a confirmed vulnerability (and confidence > 0.3).
    pub confirmed: bool,
    /// Signal descriptions that survived baseline filtering.
    pub signals: Vec<String>,
    /// Signals that were suppressed because the baseline also triggered them.
    pub suppressed: Vec<String>,
    /// Where this payload came from (table, user input, or evolutionary).
    pub source: PayloadSource,
}

/// Final result returned to the agent.
#[derive(Debug, Clone)]
pub struct FuzzResult {
    /// Confirmed hits (high-confidence vulnerabilities).
    pub confirmed: Vec<Hit>,
    /// All interesting payloads including unconfirmed.
    pub interesting: Vec<Hit>,
    /// How many probes were sent.
    pub probes_sent: usize,
    /// Final corpus size (seeds + discovered).
    pub corpus_size: usize,
    /// Baseline health summary for audit trail.
    pub baseline: String,
}

impl FuzzResult {
    pub fn has_hits(&self) -> bool { !self.confirmed.is_empty() }
}

// ── Fuzz mode ───────────────────────────────────────────────────────────

/// What kind of run to execute — table sweep, evolutionary, or hybrid.
///
/// Table and InputsOnly are exact sweeps: payloads are sent in order,
/// no corpus scheduling, no mutation, no randomness.
/// TableThenEvolutionary and Evolutionary funnel through the standard
/// evolutionary loop.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FuzzMode {
    /// Run the exact payload table once, no mutation, no randomness.
    /// Best for: predictable first-pass coverage, agent audit trails.
    Table,
    /// Run table first, seed corpus from interesting hits, then evolve.
    /// Best for: broad coverage + adaptive depth.
    TableThenEvolutionary,
    /// Pure evolutionary from seeds (current default).
    /// Best for: deep exploration, novel payload discovery.
    Evolutionary,
    /// Run only the user-supplied payloads, no built-in tables, no mutation.
    /// Best for: "try these exact payloads."
    InputsOnly,
}

// ── Vulnerability preset ────────────────────────────────────────────────

// Presets are thin — they combine a vuln class table, a signal set, and
// a default gen_ratio. The mode (Table/Evolutionary/etc.) is separate and
// controls whether the engine uses the corpus scheduler or walks linearly.

struct Preset {
    table: Option<payloads::PayloadTable>,
    atoms: Vec<String>,
    chain: ChainTable,
    seeds: Vec<String>,
    signal_set: SignalSet,
    feedback: Box<dyn Feedback>,
    gen_ratio: f32,
    placement: PlacementPolicy,
    length: LengthPolicy,
    // Mode is NOT stored here — it's on the Fuzzer builder.
}

impl Default for Preset {
    fn default() -> Self {
        Self {
            table: None,
            atoms: ATOMS.iter().map(|s| s.to_string()).collect(),
            chain: ChainTable::defaults(),
            seeds: vec![],
            signal_set: SignalSet::defaults(),
            feedback: Box::new(HttpFeedback::default()),
            gen_ratio: 0.3,
            placement: PlacementPolicy::default(),
            length: LengthPolicy::medium(),
        }
    }
}

impl Preset {
    fn sql_injection() -> Self {
        Self {
            table: Some(payloads::sqli_table()),
            atoms: ATOMS.iter().map(|s| s.to_string()).collect(),
            chain: ChainTable::defaults(),
            seeds: payloads::SQLI_PAYLOADS.iter().map(|s| s.to_string()).collect(),
            signal_set: SignalSet::new()
                .with(Box::new(StatusClassifier))
                .with(Box::new(ErrorClassifier::dbms_starter()))
                .with(Box::new(TimeDelayClassifier::default())),
            feedback: Box::new(HttpFeedback::default()),
            gen_ratio: 0.3,
            placement: PlacementPolicy::default(),
            length: LengthPolicy::medium(),
        }
    }

    fn xss() -> Self {
        Self {
            table: Some(payloads::xss_table()),
            seeds: payloads::XSS_PAYLOADS.iter().map(|s| s.to_string()).collect(),
            signal_set: SignalSet::new()
                .with(Box::new(StatusClassifier))
                .with(Box::new(ReflectionClassifier))
                .with(Box::new(BodyDiffClassifier)),
            gen_ratio: 0.3,
            ..Default::default()
        }
    }

    fn ssti() -> Self {
        Self {
            table: Some(payloads::ssti_table()),
            seeds: payloads::SSTI_PAYLOADS.iter().map(|s| s.to_string()).collect(),
            signal_set: SignalSet::new()
                .with(Box::new(StatusClassifier))
                .with(Box::new(SizeClassifier::default()))
                .with(Box::new(ReflectionClassifier))
                .with(Box::new(ErrorClassifier::dbms_starter())),
            gen_ratio: 0.3,
            ..Default::default()
        }
    }

    fn command_injection() -> Self {
        Self {
            table: Some(payloads::cmd_table()),
            seeds: payloads::CMD_PAYLOADS.iter().map(|s| s.to_string()).collect(),
            signal_set: SignalSet::new()
                .with(Box::new(StatusClassifier))
                .with(Box::new(TimeDelayClassifier::default()))
                .with(Box::new(SizeClassifier::default())),
            gen_ratio: 0.3,
            ..Default::default()
        }
    }

    fn path_traversal() -> Self {
        Self {
            table: Some(payloads::traversal_table()),
            seeds: payloads::PATH_TRAVERSAL_PAYLOADS.iter().map(|s| s.to_string()).collect(),
            signal_set: SignalSet::new()
                .with(Box::new(StatusClassifier))
                .with(Box::new(SizeClassifier::default()))
                .with(Box::new(ReflectionClassifier)),
            gen_ratio: 0.3,
            ..Default::default()
        }
    }

    fn nosql_injection() -> Self {
        Self {
            table: Some(payloads::nosqli_table()),
            seeds: payloads::NOSQLI_PAYLOADS.iter().map(|s| s.to_string()).collect(),
            signal_set: SignalSet::new()
                .with(Box::new(StatusClassifier))
                .with(Box::new(SizeClassifier::default()))
                .with(Box::new(ErrorClassifier::dbms_starter()))
                .with(Box::new(TimeDelayClassifier::default())),
            gen_ratio: 0.3,
            length: LengthPolicy::short(),
            ..Default::default()
        }
    }

    fn ssrf() -> Self {
        Self {
            table: Some(payloads::ssrf_table()),
            seeds: payloads::SSRF_PAYLOADS.iter().map(|s| s.to_string()).collect(),
            signal_set: SignalSet::new()
                .with(Box::new(StatusClassifier))
                .with(Box::new(SizeClassifier::default()))
                .with(Box::new(TimeDelayClassifier::default())),
            gen_ratio: 0.0,
            ..Default::default()
        }
    }

    fn xxe() -> Self {
        Self {
            table: Some(payloads::xxe_table()),
            seeds: payloads::XXE_PAYLOADS.iter().map(|s| s.to_string()).collect(),
            signal_set: SignalSet::new()
                .with(Box::new(StatusClassifier))
                .with(Box::new(SizeClassifier::default()))
                .with(Box::new(ReflectionClassifier)),
            gen_ratio: 0.0,
            ..Default::default()
        }
    }
}

// ── Injection point ────────────────────────────────────────────────────

/// Where the payload is injected into the request.
#[derive(Debug, Clone)]
pub enum InjectionPoint {
    /// URL-encoded into a query parameter. Produces `?name=<encoded>`.
    /// Default for GET.
    QueryParam(String),
    /// Body injection with optional template and Content-Type.
    /// `template` is a string with `{{payload}}` as placeholder.
    /// `None` = raw body (backward compatible).
    BodyRaw {
        template: Option<String>,
        content_type: Option<String>,
    },
    /// Injects into a header value (for Host, User-Agent, Cookie, etc.).
    Header(String),
    /// Appends to the URL path: `/existing/path/<payload>`.
    PathSegment,
}

impl InjectionPoint {
    /// Raw body, no template, no Content-Type.
    pub fn body_raw() -> Self {
        InjectionPoint::BodyRaw { template: None, content_type: None }
    }

    /// Form-encoded body: `key=value&param={{payload}}`.
    pub fn body_form(template: &str) -> Self {
        InjectionPoint::BodyRaw {
            template: Some(template.into()),
            content_type: Some("application/x-www-form-urlencoded".into()),
        }
    }

    /// JSON body: `{"key": "{{payload}}"}`.
    pub fn body_json(template: &str) -> Self {
        InjectionPoint::BodyRaw {
            template: Some(template.into()),
            content_type: Some("application/json".into()),
        }
    }

    /// XML body: `<key>{{payload}}</key>`.
    pub fn body_xml(template: &str) -> Self {
        InjectionPoint::BodyRaw {
            template: Some(template.into()),
            content_type: Some("application/xml".into()),
        }
    }

    /// GraphQL body: `{"query": "{ user(id: \"{{payload}}\") { name } }"}`.
    pub fn body_graphql(template: &str) -> Self {
        InjectionPoint::BodyRaw {
            template: Some(template.into()),
            content_type: Some("application/json".into()),
        }
    }

    /// Custom body with explicit Content-Type.
    pub fn body_template(content_type: &str, template: &str) -> Self {
        InjectionPoint::BodyRaw {
            template: Some(template.into()),
            content_type: Some(content_type.into()),
        }
    }
}

impl InjectionPoint {
    /// Apply the injection to a URL+method, producing a full Request.
    fn apply(&self, base_url: &str, method: &str, payload: &str) -> Request {
        match self {
            InjectionPoint::QueryParam(name) => {
                let mut url = Url::parse(base_url).unwrap_or_else(|_| {
                    Url::parse(&format!("http://{}/", base_url)).unwrap()
                });
                url.query_pairs_mut().append_pair(name, payload);
                Request {
                    url: url.to_string(),
                    method: method.to_string(),
                    headers: HashMap::new(),
                    body: String::new(),
                }
            }
            InjectionPoint::BodyRaw { template, content_type } => {
                let body = match template {
                    Some(tpl) => tpl.replace("{{payload}}", payload),
                    None => payload.to_string(),
                };
                let headers = match content_type {
                    Some(ct) => {
                        let mut h = HashMap::new();
                        h.insert("Content-Type".into(), ct.clone());
                        h
                    }
                    None => HashMap::new(),
                };
                Request {
                    url: base_url.to_string(),
                    method: method.to_string(),
                    headers,
                    body,
                }
            }
            InjectionPoint::Header(name) => {
                let mut headers = HashMap::new();
                headers.insert(name.clone(), payload.to_string());
                Request {
                    url: base_url.to_string(),
                    method: method.to_string(),
                    headers,
                    body: String::new(),
                }
            }
            InjectionPoint::PathSegment => {
                let mut url = Url::parse(base_url).unwrap_or_else(|_| {
                    Url::parse(&format!("http://{}/", base_url)).unwrap()
                });
                let path = url.path().trim_end_matches('/').to_string();
                url.set_path(&format!("{}/{}", path, payload));
                Request {
                    url: url.to_string(),
                    method: method.to_string(),
                    headers: HashMap::new(),
                    body: String::new(),
                }
            }
        }
    }
}

// ── Fuzzer builder ───────────────────────────────────────────────────────

/// High-level fuzzer interface for AI agents.
pub struct Fuzzer<P: Probe> {
    probe: Arc<P>,
    preset: Preset,
    mode: FuzzMode,
    target_url: String,
    method: String,
    injection: InjectionPoint,
    budget: usize,
    replay_seed: Option<u64>,
    request_timeout: Duration,
    additional_seeds: Vec<String>,
    stop_on_confirmation: bool,
}

impl<P: Probe> Fuzzer<P> {
    pub fn new(probe: Arc<P>) -> Self {
        Self {
            probe,
            preset: Preset::default(),
            mode: FuzzMode::Evolutionary,
            target_url: String::new(),
            method: "GET".into(),
            injection: InjectionPoint::QueryParam("q".into()),
            budget: 50,
            replay_seed: None,
            request_timeout: Duration::from_secs(30),
            additional_seeds: vec![],
            stop_on_confirmation: false,
        }
    }

    /// Set the fuzz mode (Table, Evolutionary, TableThenEvolutionary, InputsOnly).
    pub fn mode(mut self, m: FuzzMode) -> Self { self.mode = m; self }

    pub fn sql_injection(mut self) -> Self { self.preset = Preset::sql_injection(); self }
    pub fn xss(mut self) -> Self { self.preset = Preset::xss(); self }
    pub fn ssti(mut self) -> Self { self.preset = Preset::ssti(); self }
    pub fn command_injection(mut self) -> Self { self.preset = Preset::command_injection(); self }
    pub fn path_traversal(mut self) -> Self { self.preset = Preset::path_traversal(); self }
    pub fn nosql_injection(mut self) -> Self { self.preset = Preset::nosql_injection(); self }
    pub fn ssrf(mut self) -> Self { self.preset = Preset::ssrf(); self }
    pub fn xxe(mut self) -> Self { self.preset = Preset::xxe(); self }
    /// Convenience: table sweep with the current preset's table.
    pub fn table_sweep(mut self) -> Self { self.mode = FuzzMode::Table; self }

    pub fn target(mut self, url: &str, method: &str) -> Self {
        self.target_url = url.to_string();
        self.method = method.to_uppercase();
        // Default injection: query param for GET, body for POST
        if self.method == "POST" {
            self.injection = InjectionPoint::body_raw();
        } else {
            self.injection = InjectionPoint::QueryParam("q".into());
        }
        self
    }

    /// Inject payloads into the named query parameter (URL-encoded).
    ///
    /// Produces: `https://target/path?name=<url-encoded payload>`.
    /// Handles existing query params correctly (appends `&name=...`).
    pub fn inject_query(mut self, param: &str) -> Self {
        self.injection = InjectionPoint::QueryParam(param.into());
        self
    }

    /// Inject payloads into a header value.
    pub fn inject_header(mut self, name: &str) -> Self {
        self.injection = InjectionPoint::Header(name.into());
        self
    }

    /// Inject payloads as the raw request body (no Content-Type).
    pub fn inject_body_raw(mut self) -> Self {
        self.injection = InjectionPoint::body_raw();
        self
    }

    /// Inject payloads as a path segment: `/existing/path/<payload>`.
    pub fn inject_path(mut self) -> Self {
        self.injection = InjectionPoint::PathSegment;
        self
    }

    /// Form-encoded POST body. `{{payload}}` is substituted.
    ///
    /// Sets `Content-Type: application/x-www-form-urlencoded`.
    ///
    /// Example: `.body_form("username=admin&password={{payload}}")`
    pub fn body_form(mut self, template: &str) -> Self {
        self.injection = InjectionPoint::body_form(template);
        self
    }

    /// JSON POST body. `{{payload}}` is substituted.
    ///
    /// Sets `Content-Type: application/json`.
    ///
    /// Example: `.body_json(r#"{"search":"{{payload}}"}"#)`
    pub fn body_json(mut self, template: &str) -> Self {
        self.injection = InjectionPoint::body_json(template);
        self
    }

    /// XML POST body. `{{payload}}` is substituted.
    ///
    /// Sets `Content-Type: application/xml`.
    pub fn body_xml(mut self, template: &str) -> Self {
        self.injection = InjectionPoint::body_xml(template);
        self
    }

    /// GraphQL POST body. `{{payload}}` is substituted.
    ///
    /// Sets `Content-Type: application/json`.
    ///
    /// Example: `.body_graphql(r#"{"query":"{user(id:\"{{payload}}\"){name}}"}"#)`
    pub fn body_graphql(mut self, template: &str) -> Self {
        self.injection = InjectionPoint::body_graphql(template);
        self
    }

    /// Custom body with explicit Content-Type. `{{payload}}` is substituted.
    ///
    /// Example: `.body_template("text/plain", "prefix-{{payload}}-suffix")`
    pub fn body_template(mut self, content_type: &str, template: &str) -> Self {
        self.injection = InjectionPoint::body_template(content_type, template);
        self
    }

    pub fn budget(mut self, probes: usize) -> Self { self.budget = probes.max(1); self }

    pub fn seeds<I, S>(mut self, seeds: I) -> Self
    where I: IntoIterator<Item = S>, S: Into<String>,
    { self.additional_seeds = seeds.into_iter().map(|s| s.into()).collect(); self }

    pub fn replay_seed(mut self, seed: u64) -> Self { self.replay_seed = Some(seed); self }
    pub fn request_timeout(mut self, t: Duration) -> Self { self.request_timeout = t; self }
    pub fn gen_ratio(mut self, r: f32) -> Self { self.preset.gen_ratio = r.clamp(0.0, 1.0); self }
    pub fn stop_on_first_hit(mut self) -> Self { self.stop_on_confirmation = true; self }

    // ── Run ───────────────────────────────────────────────────────────

    pub async fn run(self) -> Result<FuzzResult, String> {
        let probe = self.probe.clone();

        // ── Baseline: same shape as fuzzed requests ──────────────────
        let injection = self.injection.clone();
        let url = self.target_url.clone();
        let method = self.method.clone();
        let baseline_req = injection.apply(&url, &method, "");
        let baseline_resp = self.probe.send(&baseline_req).await
            .map_err(|e| format!("baseline probe failed: {e}"))?;

        let baseline_profile = BaselineProfile::capture(&baseline_resp, &self.preset.signal_set);

        let inject = move |payload: &str| -> Request {
            injection.apply(&url, &method, payload)
        };

        // ── Table / InputsOnly: exact sweep — no corpus, no mutation, no randomness ──
        if matches!(self.mode, FuzzMode::Table | FuzzMode::InputsOnly) {
            let entries: Vec<(String, PayloadSource)> = match self.mode {
                FuzzMode::Table => {
                    let table = self.preset.table.as_ref()
                        .ok_or_else(|| "Table mode requires a preset with a payload table".to_string())?;
                    let preset_name = table.name.clone();
                    table.cases.iter().enumerate().map(|(i, c)| {
                        (c.payload.clone(), PayloadSource::Table { preset: preset_name.clone(), index: i })
                    }).collect()
                }
                FuzzMode::InputsOnly => {
                    self.additional_seeds.iter().enumerate().map(|(i, s)| {
                        (s.clone(), PayloadSource::UserInput { index: i })
                    }).collect()
                }
                _ => unreachable!(),
            };

            let signal_set = &self.preset.signal_set;
            let feedback = &*self.preset.feedback;
            let budget = self.budget.min(entries.len());
            let mut hits: Vec<Hit> = Vec::new();
            let mut interesting: Vec<Hit> = Vec::new();
            let mut probes_sent = 0usize;

            for (payload, source) in entries.into_iter().take(budget) {
                let req = inject(&payload);
                let resp = match tokio::time::timeout(
                    self.request_timeout, probe.send(&req)).await
                {
                    Ok(Ok(r)) => r,
                    Ok(Err(_)) => { probes_sent += 1; continue; }
                    Err(_)     => { probes_sent += 1; continue; }
                };
                probes_sent += 1;

                // Classify — then filter through baseline profile.
                let raw_signals = signal_set.run(&payload, &baseline_resp, &resp);
                let signals = baseline_profile.filter(&raw_signals);

                // Full context for feedback.
                let ctx = EvaluationContext {
                    payload: &payload,
                    request: &req,
                    baseline: &baseline_resp,
                    response: &resp,
                    probe_error: None,
                    raw_signals: &raw_signals,
                    filtered_signals: &signals,
                };
                let eval = feedback.evaluate(&ctx);

                if eval.interesting {
                    let filtered_kinds: std::collections::HashSet<&str> =
                        signals.iter().map(|s| s.kind()).collect();
                    let ambient: Vec<Signal> = raw_signals
                        .into_iter()
                        .filter(|s| !filtered_kinds.contains(s.kind()))
                        .collect();

                    let confidence = baseline_profile.confidence();
                    let hit = Hit {
                        payload,
                        raw_score: eval.score,
                        confidence,
                        adjusted_score: eval.score as f32 * confidence,
                        confirmed: eval.confirmed && confidence > 0.3,
                        signals: signals.iter().map(|s| s.kind().to_string()).collect(),
                        suppressed: ambient.iter().map(|s| s.kind().to_string()).collect(),
                        source,
                    };

                    if hit.confirmed {
                        hits.push(hit.clone());
                    }
                    interesting.push(hit);

                    if eval.confirmed && self.stop_on_confirmation {
                        break;
                    }
                }
            }

            return Ok(FuzzResult {
                confirmed: hits,
                interesting,
                probes_sent,
                corpus_size: 0,
                baseline: baseline_profile.summary(),
            });
        }

        // ── TableThenEvolutionary: exact sweep then evolve ──
        let mut extra_seeds: Vec<String> = Vec::new();
        if matches!(self.mode, FuzzMode::TableThenEvolutionary) {
            let table = self.preset.table.as_ref()
                .ok_or_else(|| "TableThenEvolutionary requires a preset with a payload table".to_string())?;
            let entries: Vec<String> = table.cases.iter().map(|c| c.payload.clone()).collect();
            let signal_set = &self.preset.signal_set;
            let feedback = &*self.preset.feedback;
            let sweep_budget = self.budget.min(entries.len());
            for payload in entries.into_iter().take(sweep_budget) {
                let req = inject(&payload);
                let resp = match tokio::time::timeout(self.request_timeout, probe.send(&req)).await {
                    Ok(Ok(r)) => r,
                    _ => continue,
                };
                let raw = signal_set.run(&payload, &baseline_resp, &resp);
                let sigs = baseline_profile.filter(&raw);
                let ctx = EvaluationContext { payload: &payload, request: &req, baseline: &baseline_resp, response: &resp, probe_error: None, raw_signals: &raw, filtered_signals: &sigs };
                if feedback.evaluate(&ctx).interesting {
                    extra_seeds.push(payload);
                }
            }
        }

        // ── Evolutionary path (TableThenEvolutionary, Evolutionary) ──
        let sampler = WeightedSampler::new(
            self.preset.atoms,
            self.preset.chain,
            self.preset.placement,
            self.preset.length,
        );
        let havoc = HavocMutator::new(sampler.clone(), self.budget * 4);
        let mut corpus = SeedCorpus::from_seeds(&self.preset.seeds);
        for s in &self.additional_seeds {
            corpus.push_seed(s.clone());
        }
        for s in &extra_seeds {
            corpus.push_seed(s.clone());
        }

        let mut loop_ = EvolutionaryLoop::new(
            probe,
            corpus,
            sampler,
            havoc,
            self.preset.feedback,
        )
        .with_gen_ratio(self.preset.gen_ratio)
        .with_max_probes(self.budget)
        .with_signal_set(self.preset.signal_set)
        .with_request_timeout(self.request_timeout);

        if self.stop_on_confirmation { loop_ = loop_.stop_on_first_hit(); }
        if let Some(s) = self.replay_seed { loop_ = loop_.with_seed(s); }

        // Run with pre-captured baseline — no duplicate request.
        let outcome = loop_.run_with_baseline(baseline_resp, inject).await?;

        let profile = &outcome.baseline_profile;
        let confidence = profile.confidence();

        let to_hit = |h: &EvolutionaryHit| {
            let source = match self.mode {
                FuzzMode::Table | FuzzMode::TableThenEvolutionary => {
                    if h.parent_idx < self.preset.table.as_ref().map(|t| t.len()).unwrap_or(0) {
                        PayloadSource::Table {
                            preset: self.preset.table.as_ref()
                                .map(|t| t.name.clone()).unwrap_or_default(),
                            index: h.parent_idx,
                        }
                    } else {
                        PayloadSource::Evolutionary
                    }
                }
                FuzzMode::InputsOnly => {
                    PayloadSource::UserInput { index: h.parent_idx }
                }
                FuzzMode::Evolutionary => PayloadSource::Evolutionary,
            };
            Hit {
                payload: h.payload.clone(),
                raw_score: h.score,
                confidence,
                adjusted_score: h.score as f32 * confidence,
                confirmed: h.confirmed && confidence > 0.3,
                signals: h.signals.iter().map(|s| s.kind().to_string()).collect(),
                suppressed: h.ambient.iter().map(|s| s.kind().to_string()).collect(),
                source,
            }
        };

        Ok(FuzzResult {
            confirmed: outcome.hits.iter().map(to_hit).filter(|h| h.confirmed).collect(),
            interesting: outcome.interesting.iter().map(to_hit).collect(),
            probes_sent: outcome.probes_sent,
            corpus_size: outcome.final_corpus_size,
            baseline: profile.summary(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;

    /// Mock probe that returns 500 + SQL error when payload contains ' OR.
    struct MockSqlTarget;
    #[async_trait]
    impl Probe for MockSqlTarget {
        async fn send(&self, req: &Request) -> Result<ProbeResponse, String> {
            let p = req.url.split("?q=").nth(1).unwrap_or("");
            if p.contains("' OR") || p.contains("' AND") || p.contains("UNION") {
                Ok(ProbeResponse { status: 500, body: format!("SQL error near '{p}'").into_bytes(), duration: Duration::from_millis(2) })
            } else {
                Ok(ProbeResponse { status: 200, body: b"ok".to_vec(), duration: Duration::from_millis(1) })
            }
        }
    }

    #[tokio::test]
    async fn table_mode_zero_divergence() {
        let probe = Arc::new(MockSqlTarget);

        async fn run_one(probe: Arc<MockSqlTarget>) -> FuzzResult {
            Fuzzer::new(probe)
                .sql_injection()
                .mode(FuzzMode::Table)
                .target("http://x/?q=", "GET")
                .inject_query("q")
                .budget(68)
                .replay_seed(42)
                .stop_on_first_hit()
                .run()
                .await
                .unwrap()
        }

        let r1 = run_one(probe.clone()).await;
        let r2 = run_one(probe.clone()).await;

        // Same number of hits
        assert_eq!(r1.confirmed.len(), r2.confirmed.len(), "confirmed count diverged");
        assert_eq!(r1.interesting.len(), r2.interesting.len(), "interesting count diverged");
        assert_eq!(r1.probes_sent, r2.probes_sent, "probes_sent diverged");

        // Same hits in same order
        for (i, (h1, h2)) in r1.confirmed.iter().zip(r2.confirmed.iter()).enumerate() {
            assert_eq!(h1.payload, h2.payload, "hit {i} payload diverged");
            assert_eq!(h1.raw_score, h2.raw_score, "hit {i} raw_score diverged");
            assert!((h1.confidence - h2.confidence).abs() < 0.001, "hit {i} confidence diverged");
            assert_eq!(h1.signals, h2.signals, "hit {i} signals diverged");
            // Provenance must be stable
            match (&h1.source, &h2.source) {
                (PayloadSource::Table { preset: p1, index: i1 }, PayloadSource::Table { preset: p2, index: i2 }) => {
                    assert_eq!(p1, p2, "hit {i} source preset diverged");
                    assert_eq!(i1, i2, "hit {i} source index diverged");
                }
                _ => panic!("hit {i} source type diverged"),
            }
        }

        // Interesting list also matches (includes unconfirmed)
        for (i, (h1, h2)) in r1.interesting.iter().zip(r2.interesting.iter()).enumerate() {
            assert_eq!(h1.payload, h2.payload, "interesting[{i}] payload diverged");
        }
    }

    #[tokio::test]
    async fn table_mode_replay_matches_across_seeds() {
        let probe = Arc::new(MockSqlTarget);

        async fn run_one(probe: Arc<MockSqlTarget>, seed: u64) -> FuzzResult {
            Fuzzer::new(probe)
                .sql_injection()
                .mode(FuzzMode::Table)
                .target("http://x/?q=", "GET")
                .inject_query("q")
                .budget(30)
                .replay_seed(seed)
                .run()
                .await
                .unwrap()
        }

        let r1 = run_one(probe.clone(), 0).await;
        let r2 = run_one(probe.clone(), 0).await;
        assert_eq!(r1.confirmed.len(), r2.confirmed.len());

        let r3 = run_one(probe.clone(), 1).await;
        let r4 = run_one(probe.clone(), 1).await;
        assert_eq!(r3.confirmed.len(), r4.confirmed.len());
    }

    /// Table mode sends exact payloads in order — no mutation, no randomness.
    #[tokio::test]
    async fn table_mode_sends_exact_payloads_in_order() {
        use std::sync::Mutex;

        struct OrderRecordingProbe {
            seen: Mutex<Vec<String>>,
        }

        #[async_trait]
        impl Probe for OrderRecordingProbe {
            async fn send(&self, req: &Request) -> Result<ProbeResponse, String> {
                self.seen.lock().unwrap().push(req.body.clone());
                Ok(ProbeResponse { status: 200, body: b"ok".to_vec(), duration: Duration::from_millis(1) })
            }
        }

        let order_probe = Arc::new(OrderRecordingProbe { seen: Mutex::new(Vec::new()) });
        let order_clone = order_probe.clone();

        let result = Fuzzer::new(order_probe)
            .sql_injection()
            .mode(FuzzMode::Table)
            .target("http://x/", "POST")
            .inject_body_raw()
            .budget(5)
            .run()
            .await
            .unwrap();

        let seen = order_clone.seen.lock().unwrap();
        // First 5 SQLI_PAYLOADS: "'", "\"", "' OR '1'='1", "\" OR \"1\"=\"1", "' OR 1=1--"
        assert_eq!(seen.len(), 6, "should send exactly 5 payloads (budget + baseline)");
        assert_eq!(seen[1], "'", "baseline + first payload should be exact table entry");
        assert_eq!(seen[2], "\"", "second payload should be exact table entry");
        assert_eq!(seen[3], "' OR '1'='1", "third payload should be exact table entry");
        assert_eq!(seen[4], "\" OR \"1\"=\"1", "fourth payload should be exact table entry");
        assert_eq!(seen[5], "' OR 1=1--", "fifth payload should be exact table entry");

        assert_eq!(result.corpus_size, 0, "table mode should have no corpus");
        assert_eq!(result.probes_sent, 5, "probes_sent should match budget");
    }

    /// InputsOnly mode sends user-supplied payloads exactly, in order.
    #[tokio::test]
    async fn inputs_only_sends_exact_user_inputs() {
        use std::sync::Mutex;

        struct RecProbe { seen: Mutex<Vec<String>> }
        #[async_trait]
        impl Probe for RecProbe {
            async fn send(&self, req: &Request) -> Result<ProbeResponse, String> {
                self.seen.lock().unwrap().push(req.body.clone());
                Ok(ProbeResponse { status: 200, body: b"ok".to_vec(), duration: Duration::from_millis(1) })
            }
        }

        let probe = Arc::new(RecProbe { seen: Mutex::new(Vec::new()) });
        let probe_clone = probe.clone();

        let result = Fuzzer::new(probe)
            .sql_injection()
            .mode(FuzzMode::InputsOnly)
            .target("http://x/", "POST")
            .inject_body_raw()
            .seeds(["a", "b", "c", "d", "e"].iter().map(|s| s.to_string()))
            .budget(3)
            .run()
            .await
            .unwrap();

        let seen = probe_clone.seen.lock().unwrap();
        assert_eq!(seen.len(), 4, "baseline + budget 3 should send 3 payloads");
        assert_eq!(&seen[1..], &["a", "b", "c"], "user payloads sent in order");

        assert_eq!(result.corpus_size, 0, "inputs-only mode should have no corpus");
        assert_eq!(result.probes_sent, 3);
        // Provenance: all hits (none here) but interesting should have InputsOnly source
        // With status 200, nothing is interesting. Just verify runs clean.
    }
}
